export const fakeUsers = [
  {
    email: "george.bluth@reqres.in",
    favorite: false,
    first_name: "George",
    last_name: "Bluth",
  },
  {
    email: "janet.weaver@reqres.in",
    favorite: false,
    first_name: "Janet",
    last_name: "Weaver",
  },
  {
    email: "emma.wong@reqres.in",
    favorite: false,
    first_name: "Emma",
    last_name: "Wong",
  },
  {
    email: "eve.holt@reqres.in",
    favorite: false,
    first_name: "Eve",
    last_name: "Holt",
  },
  {
    email: "charles.morris@reqres.in",
    favorite: false,
    first_name: "Charles",
    last_name: "Morris",
  },
  {
    email: "tracey.ramos@reqres.in",
    favorite: false,
    first_name: "Tracey",
    last_name: "Ramos",
  },
  {
    email: "michael.lawson@reqres.in",
    favorite: false,
    first_name: "Michael",
    last_name: "Lawson",
  },
  {
    email: "lindsay.ferguson@reqres.in",
    favorite: false,
    first_name: "Lindsay",
    last_name: "Ferguson",
  },
  {
    email: "tobias.funke@reqres.in",
    favorite: false,
    first_name: "Tobias",
    last_name: "Funke",
  },
  {
    email: "byron.fields@reqres.in",
    favorite: false,
    first_name: "Byron",
    last_name: "Fields",
  },
  {
    email: "george.edwards@reqres.in",
    favorite: false,
    first_name: "George",
    last_name: "Edwards",
  },
  {
    email: "rachel.howell@reqres.in",
    favorite: false,
    first_name: "Rachel",
    last_name: "Howell",
  },
  {
    email: "michael.scott@reqres.in",
    favorite: false,
    first_name: "Michael",
    last_name: "Scott",
  },
  {
    email: "pam.beesly@reqres.in",
    favorite: false,
    first_name: "Pam",
    last_name: "Beesly",
  },
  {
    email: "jim.halpert@reqres.in",
    favorite: false,
    first_name: "Jim",
    last_name: "Halpert",
  },
  {
    email: "dwight.schrute@reqres.in",
    favorite: false,
    first_name: "Dwight",
    last_name: "Schrute",
  },
  {
    email: "angela.martin@reqres.in",
    favorite: false,
    first_name: "Angela",
    last_name: "Martin",
  },
  {
    email: "kevin.malone@reqres.in",
    favorite: false,
    first_name: "Kevin",
    last_name: "Malone",
  },
  {
    email: "oscar.martinez@reqres.in",
    favorite: false,
    first_name: "Oscar",
    last_name: "Martinez",
  },
  {
    email: "stanley.hudson@reqres.in",
    favorite: false,
    first_name: "Stanley",
    last_name: "Hudson",
  },
];
